version: '3.8'

services:
  app:
    build: .
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      working_dir: /var/www/
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/atc/php/conf.d/local.ini
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge