apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: default
type: Opaque
data:
  APP_KEY: <base64-encoded-app-key>
  DB_PASSWORD: <base64-encoded-db-password>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        root /var/www/html/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: laravel:latest
        envFrom:
        - secretRef:
            name: laravel-secret
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/html/storage
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          subPath: default.conf
      volumes:
      - name: app-storage
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: default
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP