apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel-app
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: laravel:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: "local"
        - name: APP_DEBUG
          value: "true"
        - name: APP_KEY
          value: "base64:generatedkey123456789012345678901234567890"
        - name: APP_URL
          value: "http://localhost:8000"
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "laravel_db"
        - name: DB_USERNAME
          value: "laravel_user"
        - name: DB_PASSWORD
          value: "laravel_password"
        - name: LOG_CHANNEL
          value: "stderr"
        # Add resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Improved probes dengan initial delay yang lebih lama
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 120  # Beri waktu lebih lama untuk startup
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60   # Kurangi delay untuk readiness
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 30     # Beri waktu hingga 300 detik untuk startup
          periodSeconds: 10
        # Lifecycle hooks
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 'Container started' > /tmp/startup.log"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"]