apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel-app
type: Opaque
stringData:
  mysql-root-password: "rootpassword"
  mysql-password: "laravel_password"
  mysql-database: "laravel_db"
  mysql-user: "laravel_user"